<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="AmaZend">
    <meta name="author" content="">
    <meta name="keywords" content="">

    <title>
        Category
    </title>

    <meta name="keywords" content="">

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100' rel='stylesheet' type='text/css'>

    
    <script src="js/respond.min.js"></script>

    <link rel="shortcut icon" href="favicon.png">



</head>

<body>
    <div id="all">

        <div id="content">
            <div class="container">

                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a href="#">Home</a>
                        </li>
                        <li><?php $c=$this->category_name; if($this->language=="En"){echo $c['cat_EnName'];}else{echo $c['cat_ArName'];} ?></li>
                    </ul>
                </div>

                <div class="col-md-12">
                    <div class="box">
                        <h1>Top Product</h1>
                        <!--<p>In our Ladies department we offer wide selection of the best products we have found and carefully selected worldwide.</p>-->
                    </div>

                    <?php $top_prod=$this->cat_details ?>
                    <!-- top product Start -->
                    <div class="row products">
                        <div class="col-md-4 col-sm-6">
                            <div class="product">
                                <div class="flip-container">
                                    <div class="flipper">
                                        <div class="front">
                                            <a href="/index/product/pid/<?=$top_prod[0]['productID'] ?>">
                                                <img src="/img/<?=$top_prod[0]['photo'] ?>" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                        <div class="back">
                                            <a href="/index/product/pid/<?=$top_prod[0]['productID'] ?>">
                                                <img src="/img/<?=$top_prod[0]['photo'] ?>" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <a href="/index/product/pid/<?=$top_prod[0]['productID'] ?>" class="invisible">
                                    <img src="/img/<?=$value['photo'] ?>" alt="" class="img-responsive">
                                </a>
                                <div class="text">
                                    <h3><a href="/index/product/pid/<?=$top_prod[0]['productID'] ?>">
                                            <?php if($this->language=="En"){echo $top_prod[0]['EnName'];}else{echo $top_prod[0]['ArName'];} ?>
                                        </a></h3>
                                    <p class="price">$<?= $top_prod[0]['price'] ?></p>
                                    <p class="buttons">
                                        <a href="/index/product/pid/<?=$top_prod[0]['productID'] ?>" class="btn btn-default">View detail</a>
                                        <a href="/customer/addcart/pid/<?=$top_prod[0]['productID'] ?>" class="btn btn-primary"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                    </p>
                                </div>
                                <!-- /.text -->
                            </div>
                            <!-- /.product -->
                        </div>

                    </div>
                    <!-- /.top product end -->
                    
                    <div class="box">
                        <h1><?php $c=$this->category_name; if($this->language=="En"){echo $c['cat_EnName'];}else{echo $c['cat_ArName'];} ?></h1>
                        <!--<p>In our Ladies department we offer wide selection of the best products we have found and carefully selected worldwide.</p>-->
                    </div>
                    <div class="row products">
                        
<?php 
$products=$this->cat_details;
foreach ($products as $key=>$value)
    { ?>
                        <div class="col-md-4 col-sm-6">
                            <div class="product">
                                <div class="flip-container">
                                    <div class="flipper">
                                        <div class="front">
                                            <a href="/index/product/pid/<?=$value['productID'] ?>">
                                                <img src="/img/<?=$value['photo'] ?>" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                        <div class="back">
                                            <a href="/index/product/pid/<?=$value['productID'] ?>">
                                                <img src="/img/<?=$value['photo'] ?>" alt="" class="img-responsive">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <a href="/index/product/pid/<?=$value['productID'] ?>" class="invisible">
                                    <img src="/img/<?=$value['photo'] ?>" alt="" class="img-responsive">
                                </a>
                                <div class="text">
                                    <h3><a href="/index/product/pid/<?=$value['productID'] ?>">
                                            <?php if($this->language=="En"){echo $value['EnName'];}else{echo $value['ArName'];} ?>
                                        </a></h3>
                                    <p class="price">$<?= $value['price'] ?></p>
                                    <p class="buttons">
                                        <a href="/index/product/pid/<?=$value['productID'] ?>" class="btn btn-default">View detail</a>
                                        <a href="/customer/addcart/pid/<?=$value['productID'] ?>" class="btn btn-primary"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                    </p>
                                </div>
                                <!-- /.text -->
                            </div>
                            <!-- /.product -->
                        </div>

<?php } ?>



                    </div>
                    <!-- /.products -->

                    <div class="pages">

                        <p class="loadMore">
                            <a href="#" class="btn btn-primary btn-lg"><i class="fa fa-chevron-down"></i> Load more</a>
                        </p>

                        <ul class="pagination">
                            <li><a href="#">&laquo;</a>
                            </li>
                            <li class="active"><a href="#">1</a>
                            </li>
                            <li><a href="#">2</a>
                            </li>
                            <li><a href="#">3</a>
                            </li>
                            <li><a href="#">4</a>
                            </li>
                            <li><a href="#">5</a>
                            </li>
                            <li><a href="#">&raquo;</a>
                            </li>
                        </ul>
                    </div>


                </div>
                <!-- /.col-md-9 -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /#content -->




    </div>
    <!-- /#all -->


    

    <!-- *** SCRIPTS TO INCLUDE ***
 _________________________________________________________ -->
    
    <script src="js/jquery.cookie.js"></script>
    <script src="js/waypoints.min.js"></script>
    <script src="js/modernizr.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/front.js"></script>






</body>

</html>