<!DOCTYPE html>
<html lang="en">
    <?php
    $userType = new Zend_Session_Namespace('user');
    $personKey = $userType->type;
//    echo $personKey;
    ?>
    <head>

        <meta charset="utf-8">
        <meta name="robots" content="all,follow">
        <meta name="googlebot" content="index,follow,snippet,archive">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="AmaZend">
        <meta name="author" content="Ondrej Svestka | ondrejsvestka.cz">
        <meta name="keywords" content="">

        <title>
            AmaZend
        </title>

        <meta name="keywords" content="">

        <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100' rel='stylesheet' type='text/css'>

        <!-- styles -->
        <link href="/css/font-awesome.css" rel="stylesheet">
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <link href="/css/animate.min.css" rel="stylesheet">
        <link href="/css/owl.carousel.css" rel="stylesheet">
        <link href="/css/owl.theme.css" rel="stylesheet">

        <!-- theme stylesheet -->
        <link href="/css/style.default.css" rel="stylesheet" id="theme-stylesheet">

        <!-- your stylesheet with modifications -->
        <link href="/css/custom.css" rel="stylesheet">

        <script src="/js/respond.min.js"></script>

        <link rel="shortcut icon" href="favicon.png">



    </head>

    <body>

        <div id="all">

            <div id="content">

                <div class="container">
                    <div class="col-md-12">
                        <div id="main-slider">
                            <?php $count = 0 ?>
                            <?php foreach ($this->slider_products as $slider_product) { ?>
                                    <?php if ($count == 0) { ?>
                                    <div class="item">
                                        <img src="/img/<?=$slider_product['photo'] ?>" alt="" class="img-responsive">
                                    </div>
    <?php } else { ?>
                                    <div class="item">
                                        <img class="img-responsive" src="/img/<?= $slider_product['photo'] ?>" alt="">
                                    </div>
                                <?php
                                }
                                $count++;
                            }
                            ?>

                        </div>
                        <!-- /#main-slider -->
                    </div>
                </div>

                <!-- *** ADVANTAGES HOMEPAGE ***
     _________________________________________________________ -->
                <div id="advantages">

                    <div class="container">
                        <div class="same-height-row">
                            <div class="col-sm-4">
                                <div class="box same-height clickable">
                                    <div class="icon"><i class="fa fa-heart"></i>
                                    </div>

                                    <h3><a href="#">We love our customers</a></h3>
                                    <p>We are known to provide best possible service ever</p>
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <div class="box same-height clickable">
                                    <div class="icon"><i class="fa fa-tags"></i>
                                    </div>

                                    <h3><a href="#">Best prices</a></h3>
                                    <p>AmaZend is the best price ever.</p>
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <div class="box same-height clickable">
                                    <div class="icon"><i class="fa fa-thumbs-up"></i>
                                    </div>

                                    <h3><a href="#">100% satisfaction guaranteed</a></h3>
                                    <p>Free returns on everything for 3 months.</p>
                                </div>
                            </div>
                        </div>
                        <!-- /.row -->

                    </div>
                    <!-- /.container -->

                </div>
                <!-- /#advantages -->

                <!-- *** ADVANTAGES END *** -->

                <!-- *** HOT PRODUCT SLIDESHOW ***
     _________________________________________________________ -->
                <div id="hot">

                    <div class="box">
                        <div class="container">
                            <div class="col-md-12">
                                <h2>Hot this week</h2>
                            </div>
                        </div>
                    </div>

                    <div class="container">
                        <div class="row">
                            <?php
                            $products = $this->products;
                            foreach ($products as $product):
                                ?>

                                <div class="col-md-3">
                                    <div class="item">
                                        <div class="product">
                                            <div class="flip-container">
                                                <div class="flipper">
                                                    <div class="front">
                                                        <a href="detail.html">
                                                            <img src="/img/product2.jpg" alt="" class="img-responsive">
                                                        </a>
                                                    </div>
                                                    <div class="back">
                                                        <a href="detail.html">
                                                            <img src="/img/product2_2.jpg" alt="" class="img-responsive">
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                            <a href="<?= "/index/product/pid/" . $product['productID'] ?>" class="invisible">
                                                <img src="/img/product2.jpg" alt="" class="img-responsive">
                                            </a>
                                            <div class="text">
                                                <?php if ($this->language == "En") { ?>
                                                    <h3><a href="<?= "/index/product/pid/" . $product['productID'] ?>"><?= $product['EnName'] ?></a></h3>
    <?php } else if ($this->language == "Ar") { ?>
                                                    <h3><a href="<?= "/index/product/pid/" . $product['productID'] ?>"><?= $product['ArName'] ?></a></h3>
    <?php } ?>

                                                <p class="price"><del>$280</del> $143.00</p>
                                            </div>
                                            <!-- /.text -->

                                            <div class="ribbon sale">
                                                <div class="theribbon">SALE</div>
                                                <div class="ribbon-background"></div>
                                            </div>
                                            <!-- /.ribbon -->

                                            <div class="ribbon new">
                                                <div class="theribbon">NEW</div>
                                                <div class="ribbon-background"></div>
                                            </div>
                                            <!-- /.ribbon -->

                                            <div class="ribbon gift">
                                                <div class="theribbon">GIFT</div>
                                                <div class="ribbon-background"></div>
                                            </div>
                                            <!-- /.ribbon -->
                                        </div>
                                        <!-- /.product -->
                                    </div>
                                    <!-- /.col-md-4 -->
                                </div>
<?php endforeach; ?>

                            <!--</div>-->
                            <!-- /.product-slider -->
                        </div>
                        <!-- /.container -->

                    </div>
                    <!-- /#hot -->

                    <!-- *** HOT END *** -->

                    <!-- *** GET INSPIRED ***
         _________________________________________________________ -->
                    <div class="container" data-animate="fadeInUpBig">
                        <div class="col-md-12">
                            <div class="box slideshow">
                                <h3>Get Inspired</h3>
                                <p class="lead">Get the inspiration from our world class designers</p>
                                <div id="get-inspired" class="owl-carousel owl-theme">
                                    <div class="item">
                                        <a href="#">
                                            <img src="/img/getinspired1.jpg" alt="Get inspired" class="img-responsive">
                                        </a>
                                    </div>
                                    <div class="item">
                                        <a href="#">
                                            <img src="/img/getinspired2.jpg" alt="Get inspired" class="img-responsive">
                                        </a>
                                    </div>
                                    <div class="item">
                                        <a href="#">
                                            <img src="/img/getinspired3.jpg" alt="Get inspired" class="img-responsive">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- *** GET INSPIRED END *** -->

                </div>
                <!-- /#content -->

              
            </div>
            <!-- /#all -->

            <!-- *** SCRIPTS TO INCLUDE ***
         _________________________________________________________ -->
            <script src="/js/jquery.cookie.js"></script>
            <script src="/js/waypoints.min.js"></script>
            <script src="/js/modernizr.js"></script>
            <script src="/js/owl.carousel.min.js"></script>
            <script src="/js/front.js"></script>


    </body>

</html>
