<!DOCTYPE html>
<html lang="en">
    <?php
    $userType = new Zend_Session_Namespace('user');
////    $userType = new Zend_Session_Namespace('userType');
$personKey= $userType->type ;
var_dump($personKey);
    ?>
    <head>

        <meta charset="utf-8">
        <meta name="robots" content="all,follow">
        <meta name="googlebot" content="index,follow,snippet,archive">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Amazend">
        <meta name="author" content="">
        <meta name="keywords" content="">

        <title>
            Products
        </title>

        <meta name="keywords" content="">

        <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100' rel='stylesheet' type='text/css'>
        <link href="/css/style.css" rel="stylesheet" type="text/css">
        <script src="/js/respond.min.js"></script>


        <link rel="shortcut icon" href="favicon.png">



    </head>

    <body>
        <!-- **************************************************************** -->
        <form id="ratingsForm">
            <div class="stars">
      		<input type="radio" name="star" class="star-1" id="<?= $this->product["productID"]?>" />
                <label class="star-1" for="star-1" id="<?= $this->product["productID"]?>">1</label>
      		<input type="radio" name="star" class="star-2" id="<?= $this->product["productID"]?>" />
                <label class="star-2" for="star-2" id="<?= $this->product["productID"]?>">2</label>
      		<input type="radio" name="star" class="star-3" id="<?= $this->product["productID"]?>" />
                <label class="star-3" for="star-3" id="<?= $this->product["productID"]?>">3</label>
      		<input type="radio" name="star" class="star-4" id="<?= $this->product["productID"]?>" />
                <label class="star-4" for="star-4" id="<?= $this->product["productID"]?>">4</label>
      		<input type="radio" name="star" class="star-5" id="<?= $this->product["productID"]?>" />
                <label class="star-5" for="star-5" id="<?= $this->product["productID"]?>">5</label>
                <span></span>
            </div>

        </form>
        <!--  ****************************************************************************************-->
        <div id="all">

            <div id="content">
                <div class="container">

                    <div class="col-md-12">
                        <ul class="breadcrumb">
                            <li><a href="/index">Home</a>
                            </li>
                            <li><a href="#"><?= $this->product["cat_EnName"] ?></a>
                            </li>
                            <li><?= $this->product["EnName"] ?></li>
                        </ul>

                    </div>

                    <div class="col-md-3">
                        <!-- *** MENUS AND FILTERS ***
     _________________________________________________________ -->
                        <div class="panel panel-default sidebar-menu">

                            <div class="panel-heading">
                                <h3 class="panel-title">Categories</h3>
                            </div>

                            <div class="panel-body">
                                <ul class="nav nav-pills nav-stacked category-menu">
                                    <li>
                                        <a href="category.html">Men <span class="badge pull-right">42</span></a>
                                        <ul>
                                            <li><a href="category.html">T-shirts</a>
                                            </li>
                                            <li><a href="category.html">Shirts</a>
                                            </li>
                                            <li><a href="category.html">Pants</a>
                                            </li>
                                            <li><a href="category.html">Accessories</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="active">
                                        <a href="category.html">Ladies  <span class="badge pull-right">123</span></a>
                                        <ul>
                                            <li><a href="category.html">T-shirts</a>
                                            </li>
                                            <li><a href="category.html">Skirts</a>
                                            </li>
                                            <li><a href="category.html">Pants</a>
                                            </li>
                                            <li><a href="category.html">Accessories</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="category.html">Kids  <span class="badge pull-right">11</span></a>
                                        <ul>
                                            <li><a href="category.html">T-shirts</a>
                                            </li>
                                            <li><a href="category.html">Skirts</a>
                                            </li>
                                            <li><a href="category.html">Pants</a>
                                            </li>
                                            <li><a href="category.html">Accessories</a>
                                            </li>
                                        </ul>
                                    </li>

                                </ul>

                            </div>
                        </div>


                        <!-- *** MENUS AND FILTERS END *** -->

                        <div class="banner">
                            <a href="#">
                                <img src="/img/banner.jpg" alt="sales 2014" class="img-responsive">
                            </a>
                        </div>
                    </div>

                    <div class="col-md-9">

                        <div class="row" id="productMain">
                            <div class="col-sm-6">
                                <div id="mainImage">
                                    <img src="/img/detailbig1.jpg" alt="" class="img-responsive">
                                </div>

                                <div class="ribbon sale">
                                    <div class="theribbon">SALE</div>
                                    <div class="ribbon-background"></div>
                                </div>
                                <!-- /.ribbon -->

                                <div class="ribbon new">
                                    <div class="theribbon">NEW</div>
                                    <div class="ribbon-background"></div>
                                </div>
                                <!-- /.ribbon -->

                            </div>
                            <div class="col-sm-6">
                                <div class="box">
                                    <h1 class="text-center">
                                        <?php
                                        if ($this->language == "En") {
                                            echo $this->product["EnName"];
                                        } elseif ($this->language == "Ar") {
                                            echo $this->product["ArName"];
                                        }
                                        ?></h1>
                                    <p class="goToDescription"><a href="#details" class="scroll-to">Scroll to product details, material & care and sizing</a>
                                    </p>
                                    <p class="price">$<?= $this->product["price"] ?></p>
<?php if($personKey== "customerID"): ?>
                                    <p class="text-center buttons">
                                        <a href="/Customer/addcart/pid/<?= $this->product['productID'] ?>" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Add to cart </a>
                                        <a href="/Customer/addwish/pid/<?= $this->product['productID'] ?>" class="btn btn-default"><i class="fa fa-heart"></i> Add to wishlist</a>
                                    </p>
                                    <?php else: ?>
                                    <p class="text-center buttons">
                                        <a href="/customer/login" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Add to cart </a>
                                        <a href="/customer/login" class="btn btn-default"><i class="fa fa-heart"></i> Add to wishlist</a>
                                    </p>
<?php endif; ?>

                                </div>

                                <div class="row" id="thumbs">
                                    <div class="col-xs-4">
                                        <a href="/img/detailbig1.jpg" class="thumb">
                                            <img src="/img/detailsquare.jpg" alt="" class="img-responsive">
                                        </a>
                                    </div>
                                    <div class="col-xs-4">
                                        <a href="/img/detailbig2.jpg" class="thumb">
                                            <img src="/img/detailsquare2.jpg" alt="" class="img-responsive">
                                        </a>
                                    </div>
                                    <div class="col-xs-4">
                                        <a href="/img/detailbig3.jpg" class="thumb">
                                            <img src="/img/detailsquare3.jpg" alt="" class="img-responsive">
                                        </a>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div>

                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs" role="tablist">
                                <?php if ($this->language == "En") { ?>
                                    <li role="presentation" class="active"><a href="#detail" aria-controls="home" role="tab" data-toggle="tab">Details</a></li>
                                <?php } else if ($this->language == "Ar") { ?>
                                    <li role="presentation" class="active"><a href="#detail" aria-controls="home" role="tab" data-toggle="tab">التفاصيل </a></li>
                                <?php } ?>
                                <?php if ($this->language == "En") { ?>
                                    <li role="presentation"><a href="#comment" aria-controls="profile" role="tab" data-toggle="tab">Comments</a></li>
                                <?php } else if ($this->language == "Ar") { ?>
                                    <li role="presentation"><a href="#comment" aria-controls="profile" role="tab" data-toggle="tab"> التعليقات </a></li>
                                <?php } ?>
                                <?php if ($personKey == "adminID") { ?>
                                    <?php if ($this->language == "En") { ?>
                                        <li role="presentation"><a href="#statistic" aria-controls="profile" role="tab" data-toggle="tab">Statistics</a></li>
                                    <?php } else if ($this->language == "Ar") { ?>
                                        <li role="presentation"><a href="#statistic" aria-controls="profile" role="tab" data-toggle="tab">الاحصائيات</a></li>
    <?php } ?>
<?php } ?>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="detail">
                                    <div class="box" id="details">
                                        <p>
                                        <?php if ($this->language == "En") { ?>
                                            <h4>Product details</h4>
                                            <p><?= $this->product["EnDescription"] ?></p>
                                        <?php } else if ($this->language == "Ar") { ?>
                                            <h4>تفاصيل المنتج </h4>
                                            <p><?= $this->product["ArDescription"] ?></p>
<?php } ?>
                                        <h4>Material & care</h4>
                                        <ul>
                                            <li>Polyester</li>
                                            <li>Machine wash</li>
                                        </ul>
                                        <h4>Size & Fit</h4>
                                        <ul>
                                            <li>Regular fit</li>
                                            <li>The model (height 5'8" and chest 33") is wearing a size S</li>
                                        </ul>

                                        <blockquote>
                                            <p><em>Define style this season with Armani's new range of trendy tops, crafted with intricate details. Create a chic statement look by teaming this lace number with skinny jeans and pumps.</em>
                                            </p>
                                        </blockquote>

                                        <hr>
                                        <div class="social">
                                            <h4>Show it to your friends</h4>
                                            <p>
                                                <a href="#" class="external facebook" data-animate-hover="pulse"><i class="fa fa-facebook"></i></a>
                                                <a href="#" class="external gplus" data-animate-hover="pulse"><i class="fa fa-google-plus"></i></a>
                                                <a href="#" class="external twitter" data-animate-hover="pulse"><i class="fa fa-twitter"></i></a>
                                                <a href="#" class="email" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div role="tabpanel" class="tab-pane" id="comment">
                                    <div class="box" id="comments">
                                            <?php foreach ($this->comments as $value) { ?>
                                            <div class="well well-sm">
    <?php echo $value['comment_body']; ?>
                                                <a href=""class="btn btn-danger">Delete</a>
                                            </div>

<?php } echo $this->comment_form; ?>

                                    </div>
                                </div>
<?php if ($personKey == "adminID") { ?>
                                    <div role="tabpanel" class="tab-pane" id="statistic">
                                        <div class="box" id="statistics">

                                            <!-- hager -->
                                            <table class="table">
                                                <tr>
                                                    <th>number of users who purchased</th>
                                                    <th>The amount of money gained </th>
                                                </tr>
                                                <?php
                                                // $pro = new Application_Model_Product();

                                                echo "<tr>" .
                                                "<td>" . $this->product["EnName"] . "</td>" .
                                                "<td>" . $this->product['no_purchase'] . "</td>" .
                                                "<td>" . $this->product['no_purchase'] * $this->product['price'] . "</td>" . "</tr>";
                                                ?>

                                            </table>


                                        </div>
                                    </div>
<?php } ?>

                            </div>

                        </div>


                        <div class="row same-height-row">
                            <div class="col-md-3 col-sm-6">
                                <div class="box same-height">
                                    <h3>You may also like these products</h3>
                                </div>
                            </div>

                            <div class="col-md-3 col-sm-6">
                                <div class="product same-height">
                                    <div class="flip-container">
                                        <div class="flipper">
                                            <div class="front">
                                                <a href="product.html">
                                                    <img src="/img/product2.jpg" alt="" class="img-responsive">
                                                </a>
                                            </div>
                                            <div class="back">
                                                <a href="product.html">
                                                    <img src="/img/product2_2.jpg" alt="" class="img-responsive">
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <a href="product.html" class="invisible">
                                        <img src="/img/product2.jpg" alt="" class="img-responsive">
                                    </a>
                                    <div class="text">
                                        <h3>Fur coat</h3>
                                        <p class="price">$143</p>
                                    </div>
                                </div>
                                <!-- /.product -->
                            </div>

                            <div class="col-md-3 col-sm-6">
                                <div class="product same-height">
                                    <div class="flip-container">
                                        <div class="flipper">
                                            <div class="front">
                                                <a href="product.html">
                                                    <img src="/img/product1.jpg" alt="" class="img-responsive">
                                                </a>
                                            </div>
                                            <div class="back">
                                                <a href="product.html">
                                                    <img src="/img/product1_2.jpg" alt="" class="img-responsive">
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <a href="product.html" class="invisible">
                                        <img src="/img/product1.jpg" alt="" class="img-responsive">
                                    </a>
                                    <div class="text">
                                        <h3>Fur coat</h3>
                                        <p class="price">$143</p>
                                    </div>
                                </div>
                                <!-- /.product -->
                            </div>


                            <div class="col-md-3 col-sm-6">
                                <div class="product same-height">
                                    <div class="flip-container">
                                        <div class="flipper">
                                            <div class="front">
                                                <a href="product.html">
                                                    <img src="/img/product3.jpg" alt="" class="img-responsive">
                                                </a>
                                            </div>
                                            <div class="back">
                                                <a href="product.html">
                                                    <img src="/img/product3_2.jpg" alt="" class="img-responsive">
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <a href="product.html" class="invisible">
                                        <img src="/img/product3.jpg" alt="" class="img-responsive">
                                    </a>
                                    <div class="text">
                                        <h3>Fur coat</h3>
                                        <p class="price">$143</p>

                                    </div>
                                </div>
                                <!-- /.product -->
                            </div>

                        </div>



                    </div>
                    <!-- /.col-md-9 -->
                </div>
                <!-- /.container -->
            </div>
            <!-- /#content -->



        </div>
        <!-- /#all -->




        <!-- *** SCRIPTS TO INCLUDE ***
     _________________________________________________________ -->
        <script src="/js/star.js" ></script>
        <script src="/js/jquery.cookie.js"></script>
        <script src="/js/waypoints.min.js"></script>
        <script src="/js/modernizr.js"></script>
        <script src="/js/owl.carousel.min.js"></script>
        <script src="/js/front.js"></script>







    </body>

</html>
