<br /><br />
<div id="view-content">
    <?php
    var_dump($this->user_wishlist);
    echo "<br><hr>";
    foreach ($this->prodcut_array as $key => $value) {
//            var_dump($value[0]);
        foreach ($value[0] as $prod_key => $prod_value) {
            print_r($prod_key.":".$prod_value."\t");
        }
        $pid=$value[0]['productID'];
        echo "<a href=/wishlist/delete-item/pid/$pid>Remove</a>";
        echo "<br><hr>";
    };
    ?>
    <a href="/wishlist/add-to-wish">Add</a>
</div>