<head>
    
    <!-- styles -->
    <link href="/css/font-awesome.css" rel="stylesheet">
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/animate.min.css" rel="stylesheet">
    <link href="/css/owl.carousel.css" rel="stylesheet">
    <link href="/css/owl.theme.css" rel="stylesheet">

    <!-- theme stylesheet -->
    <link href="/css/style.default.css" rel="stylesheet" id="theme-stylesheet">

    <!-- your stylesheet with modifications -->
    <link href="/css/custom.css" rel="stylesheet">

    <script src="/js/respond.min.js"></script>

    <link rel="shortcut icon" href="favicon.png">
</head>
<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center>New Shopper</center></h1>
  </div>
  <div class="panel-body">
	<?php
	echo $this->form;	
	?>
  </div>
</div>
</div>