<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center>New Product</center></h1>
  </div>
  <div class="panel-body">
	<?php
// 	echo $this->jQuery()->enable()
// 											->setUiVersion ( '1.8.7' )
//         ->setVersion ( '1.4.4' );
// //											->setUiVersion ( '1.12.1' )
// //                ->setVersion ( '1.12.4' );;
	echo $this->form;	
	?>
  </div>
</div>
</div>
<script type="text/javascript">
  var currentDate = new Date();
        $(".datepicker").datepicker({
            showOn: 'focus',
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy-mm-dd',
            minDate: currentDate
        });
</script>
