<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center>
    	Login Page
    </center></h1>
  </div>
  <div class="panel-body">

<?php
/*$this->title = "login";
$this->headTitle($this->title);*/
echo $this->form ;
echo $this->facebookUrl;
?>
<!-- <a href=""><img src="img/fblogin-btn.png"></a> -->
<?php echo '<a href="' . htmlspecialchars( $this->facebook_url) . '"> <img src="/img/fblogin-btn.png"></img></a>';?>

<?php //echo '<a href="/customer/fblogin"> <img src="/img/fblogin-btn.png"></img></a>';?>

<?php //echo '<a href="' . htmlspecialchars( $this->facebookUrl) . '"> <img src="/img/fblogin-btn.png"></img></a>';?>

</table>
</div>
</div>
</div>