<head>
    <!-- Latest compiled and minified CSS -->

    <!-- jQuery library -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> -->

    <!-- <link href="/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- <link href="/css/bootstrap-theme.min.css" rel="stylesheet"> -->
    <link href="/css/modified.css" rel="stylesheet">
    <!-- <script src="js/respond.min.js"></script> -->

</head>
<!-- nav header -->
<?php
//Getting category list
$cat_model = new Application_Model_Category();
$cats = $cat_model->fetchAll()->toArray();

//Getting cart items
$db = Zend_Db_Table::getDefaultAdapter(); //set in config file
$select = new Zend_Db_Select($db);
$select->from('cart', array('cartID', 'customerID')) //the array specifies which columns I want returned in my result set
        //by specifying an empty array, I am saying that I don't care about the columns from this table
        ->joinInner('cart_product', 'cart.cartID = cart_product.cartID', array())
        ->joinLeft('order_history', 'order_history.order_id=cart.cartID', array())
        ->where("customerID = 2")
        ->where('order_history.order_status_id IS NULL');
$cart_items = $db->fetchAll($select);

$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$userData = $storage->read();
$categories = new Zend_Session_Namespace('category');
// var_dump($categories->cat);
// $person = (array)$userData;
// //either shopperID or customerID
// $personKey=key($person);
// $userType = new Zend_Session_Namespace('userType');
//  $userType->type = $personKey;
//$userType->type =NULL;
//var_dump ($personKey);
//die();
?>

<!-- *************************************************************************************************** -->
<!-- *** TOPBAR ***
_________________________________________________________ -->
<div id="top">
    <div class="container">
        <div class="col-md-6 offer" data-animate="fadeInDown">
            <a href="#" class="btn btn-success btn-sm" data-animate-hover="shake">Offer of the day</a>  <a href="#">Get flat 35% off on orders over $50!</a>
        </div>
        <div class="col-md-6" data-animate="fadeInDown">
            <ul class="menu">
                <li><a href="#" data-toggle="modal" data-target="#login-modal">Login</a>
                </li>
                <li><a href="register.html">Register</a>
                </li>
                <li><a href="contact.html">Contact</a>
                </li>
                <li><a href="#">Recently viewed</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
        <div class="modal-dialog modal-sm">

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="Login">Customer login</h4>
                </div>
                <div class="modal-body">
                    <form action="customer-orders.html" method="post">
                        <div class="form-group">
                            <input type="text" class="form-control" id="email-modal" placeholder="email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" id="password-modal" placeholder="password">
                        </div>

                        <p class="text-center">
                            <button class="btn btn-primary"><i class="fa fa-sign-in"></i> Log in</button>
                        </p>

                    </form>

                    <p class="text-center text-muted">Not registered yet?</p>
                    <p class="text-center text-muted"><a href="register.html"><strong>Register now</strong></a>! It is easy and done in 1&nbsp;minute and gives you access to special discounts and much more!</p>

                </div>
            </div>
        </div>
    </div>

</div>

<!-- *** TOP BAR END *** -->

<!-- *** NAVBAR ***
_________________________________________________________ -->

<div class="navbar navbar-default yamm" role="navigation" id="navbar">
    <div class="container">
        <div class="navbar-header">

            <a class="navbar-brand home" href="/index" data-animate-hover="bounce">
                <img src="/img/logo.png" alt="Obaju logo" class="hidden-xs">
                <img src="/img/logo-small.png" alt="Obaju logo" class="visible-xs"><span class="sr-only">Obaju - go to homepage</span>
            </a>
            <div class="navbar-buttons">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <i class="fa fa-align-justify"></i>
                </button>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#search">
                    <span class="sr-only">Toggle search</span>
                    <i class="fa fa-search"></i>
                </button>
                <a class="btn btn-default navbar-toggle" href="/checkout/cart">
                    <i class="fa fa-shopping-cart"></i>  <span class="hidden-xs"><?= count($cart_items); ?> items in cart</span>
                </a>
            </div>
        </div>
        <!--/.navbar-header -->

        <div class="navbar-collapse collapse" id="navigation">

            <ul class="nav navbar-nav navbar-left">
                <li class="active"><a href="/index">Home</a>
                </li>
                <li class="dropdown yamm-fw">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">Departments <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="yamm-content">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h5>All Categories (<?= count($cats) ?>)</h5>
                                        <ul>
                                            <!--<?php foreach ($categories->cat as $category): ?>
                                                                <li><a href="/index/category/cid/<?= $category['categoryID'] ?>"><?= $category['cat_EnName'] ?></a>
                                                                </li>
                                            <?php endforeach; ?>-->
                                            <?php foreach ($cats as $category): ?>
                                                <li>
                                                    <a href="/index/category/cid/<?= $category['categoryID'] ?>"><?= $category['cat_EnName'] ?></a>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                    <!-- <div class="col-sm-3">
                                        <h5>Shoes</h5>
                                        <ul>
                                            <li><a href="category.html">Trainers</a>
                                            </li>
                                            <li><a href="category.html">Sandals</a>
                                            </li>
                                            <li><a href="category.html">Hiking shoes</a>
                                            </li>
                                            <li><a href="category.html">Casual</a>
                                            </li>
                                        </ul>
                                    </div> -->


                                </div>
                            </div>
                            <!-- /.yamm-content -->
                        </li>
                    </ul>
                </li>

                <li class="dropdown yamm-fw">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">Ladies <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="yamm-content">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <h5>Clothing</h5>
                                        <ul>
                                            <li><a href="category.html">T-shirts</a>
                                            </li>
                                            <li><a href="category.html">Shirts</a>
                                            </li>
                                            <li><a href="category.html">Pants</a>
                                            </li>
                                            <li><a href="category.html">Accessories</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-3">
                                        <h5>Shoes</h5>
                                        <ul>
                                            <li><a href="category.html">Trainers</a>
                                            </li>
                                            <li><a href="category.html">Sandals</a>
                                            </li>
                                            <li><a href="category.html">Hiking shoes</a>
                                            </li>
                                            <li><a href="category.html">Casual</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-3">
                                        <h5>Accessories</h5>
                                        <ul>
                                            <li><a href="category.html">Trainers</a>
                                            </li>
                                            <li><a href="category.html">Sandals</a>
                                            </li>
                                            <li><a href="category.html">Hiking shoes</a>
                                            </li>
                                            <li><a href="category.html">Casual</a>
                                            </li>
                                            <li><a href="category.html">Hiking shoes</a>
                                            </li>
                                            <li><a href="category.html">Casual</a>
                                            </li>
                                        </ul>
                                        <h5>Looks and trends</h5>
                                        <ul>
                                            <li><a href="category.html">Trainers</a>
                                            </li>
                                            <li><a href="category.html">Sandals</a>
                                            </li>
                                            <li><a href="category.html">Hiking shoes</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="banner">
                                            <a href="#">
                                                <img src="/img/banner.jpg" class="/img img-responsive" alt="">
                                            </a>
                                        </div>
                                        <div class="banner">
                                            <a href="#">
                                                <img src="/img/banner2.jpg" class="/img img-responsive" alt="">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.yamm-content -->
                        </li>
                    </ul>
                </li>

                <!--aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-->
                <?php if (empty($userData)) : ?>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">Login as <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="modified"><a href="/shopper/login">Shopper</a></li>
                            <li class="modified"><a href="/customer/login">Customer</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">Sign-up as <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="modified"><a href="/shopper/add">Shopper</a></li>
                            <li class="modified"><a href="/customer/add">Customer</a></li>

                            <li></li>
                        </ul>
                    </li>
                <?php else: ?>

                    <li><a href="/Customer/logout">Logout</a></li>
                <?php endif; ?>
                <!-- Language -->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">Language <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li class="modified"><a href="?ln=En">En</a></li>
                        <li class="modified"><a href="?ln=Ar">Ar</a></li>
                    </ul>
                </li>
                <!--aaaaaaaaaaaaaaaaaaaaaaaaaaaaa-->
            </ul>

        </div>
        <!--/.nav-collapse -->

        <div class="navbar-buttons">

            <div class="navbar-collapse collapse right" id="basket-overview">
                <a href="/checkout/cart" class="btn btn-primary navbar-btn"><i class="fa fa-shopping-cart"></i><span class="hidden-sm"><?= count($cart_items); ?> items in cart</span></a>
            </div>
            <!--/.nav-collapse -->

            <div class="navbar-collapse collapse right" id="search-not-mobile">
                <button type="button" class="btn navbar-btn btn-primary" data-toggle="collapse" data-target="#search">
                    <span class="sr-only">Toggle search</span>
                    <i class="fa fa-search"></i>
                </button>
            </div>

        </div>

        <div class="collapse clearfix" id="search">

            <form class="navbar-form" role="search" action="/index/search" method="GET" >
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="name">
                    <span class="input-group-btn">

                        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>

                    </span>
                </div>
            </form>

        </div>
        <!--/.nav-collapse -->

    </div>
    <!-- /.container -->
</div>
<!-- /#navbar -->


<!-- *** NAVBAR END *** -->

<?php echo $this->layout()->content; ?>

<!-- *** SCRIPTS TO INCLUDE ***
 _________________________________________________________ -->
<!-- <script src="/js/jquery-1.11.0.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/jquery.cookie.js"></script>
<script src="/js/waypoints.min.js"></script>
<script src="/js/modernizr.js"></script>
<script src="/js/bootstrap-hover-dropdown.js"></script>
<script src="/js/owl.carousel.min.js"></script>
<script src="/js/front.js"></script>
-->