<head>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.
min.css" integrity="sha384-
1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-
theme.min.css" integrity="sha384-
fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
crossorigin="anonymous"></script>

</head>
<!-- nav header -->
<?php
//set first one as customerID & retrieve it Facebook is for customers only

$fbsession = new Zend_Session_Namespace('facebook');

$auth = Zend_Auth::getInstance();
$storage= $auth->getStorage();
$userData=$storage->read();

$person = (array)$userData;
//either shopperID or customerID
$personKey=key($person);
// //var_dump ($personKey);
// //die();
?>


  <nav class="navbar-inverse" style='margin-bottom: 0'>
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href='index.php'> Amazend </a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">

  <li><a href="/index/index"> Home </a></li>
  <li><a href=""> any thing</a></li>
  <li><a href=""> About </a></li>

  <?php if(empty($userData) && !isset($fbsession->first_name) && empty (isset($fbsession->first_name)) ){ ?>

  <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login as <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="/shopper/login">Shopper</a></li>
          <li><a href="/customer/login">Customer</a></li>
        </ul>
      </li>
  <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sign-up as <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="/shopper/add">Shopper</a></li>
          <li><a href="/customer/add">Customer</a></li>

          <li></li>
        </ul>
      </li>
  <?php } else{?>

      <li><a href="/customer/logout">Logout</a></li>
      <?php } ?>

  <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">language <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">En</a></li>
          <li><a href="#">Ar</a></li>
        </ul>
      </li>
    </ul>

  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

<?php echo $this->layout()->content; ?>
