<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta name="robots" content="all,follow">
        <meta name="googlebot" content="index,follow,snippet,archive">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Obaju e-commerce template">
        <meta name="author" content="Ondrej Svestka | ondrejsvestka.cz">
        <meta name="keywords" content="">

        <title>
            Shopping Cart
        </title>

        <meta name="keywords" content="">

        <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100' rel='stylesheet' type='text/css'>

        <script src="/js/respond.min.js"></script>

        <link rel="shortcut icon" href="favicon.png">



    </head>

    <body>
        <div id="all">

            <div id="content">
                <div class="container">

                    <div class="col-md-12">
                        <ul class="breadcrumb">
                            <li><a href="#">Home</a>
                            </li>
                            <li>Shopping cart</li>
                        </ul>
                    </div>

                    <div class="col-md-9" id="basket">

                        <div class="box">

                            <form method="post" action="#">

                                <h1>Shopping cart</h1>
                                <p class="text-muted">You currently have <?= count($this->cart) ?> item(s) in your cart.</p>
                                <div class="table-responsive">
                                    <table id="cart_table" class="table">
                                        <thead>
                                            <tr>
                                                <th colspan="2">Product</th>
                                                <th>Quantity</th>
                                                <th>Unit price</th>
                                                <th>Discount</th>
                                                <th colspan="2">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            <?php
                                            $total_price = 0;
                                            $total_discount = 0;
                                            $now = new DateTime('now');
                                            foreach ($this->cart as $array => $product):

                                                $datetime1 = new DateTime($product['end']);
                                                $discount_percent = $datetime1 > $now ? $product['precent'] : 0;
                                                $discount = $discount_percent * $product['total'] / 100;
                                                $price_after_discount = $product['total'] - $discount;
                                                $total_price += $price_after_discount;
                                                $total_discount += $discount;
                                                ?>
                                                <tr>
                                                    <td>
                                                        <a href="#">
                                                            <img src="/img/detailsquare.jpg" alt="White Blouse Armani">
                                                        </a>
                                                    </td>
                                                    <td><a href="#"><?php echo$product['EnName']; ?></a>
                                                    </td>
                                                    <td>
                                                        <input class="sh7ata" type="number" min="1" value="<?= $product['quantity'] ?>" id="<?= $product['productID'] . "_" . $product['quantity'] ?>">
                                                    </td>
                                                    <td>$<?= $product['price'] ?></td>
                                                    <td>$<?php echo $discount;
                                            echo " (" . $discount_percent . "%)"
                                                ?></td>
                                                    <td>$<?= $price_after_discount ?></td>
                                                    <td><a href="/checkout/removeitem/pid/<?=$product['productID'];?>"><i class="fa fa-trash-o"></i></a>
                                                    </td>
                                                </tr>
<?php endforeach; ?>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th colspan="5">Total</th>
                                                <th colspan="2">$<?= $total_price ?></th>
                                            </tr>
                                        </tfoot>
                                    </table>

                                </div>
                                <!-- /.table-responsive -->

                                <div class="box-footer">
                                    <div class="pull-left">
                                        <a href="/index" class="btn btn-default"><i class="fa fa-chevron-left"></i> Continue shopping</a>
                                    </div>
                                    <div class="pull-right">
                                        <?php if(count($this->cart)): ?>
                                        <button class="btn btn-default" id="updatebasket"><i class="fa fa-refresh"></i> Update basket</button>
                                        <button id="placeorder" type="submit" class="btn btn-primary">Place an order <i class="fa fa-chevron-right"></i>
                                        </button>
                                        <?php endif;?>
                                    </div>
                                </div>

                            </form>

                        </div>
                        <!-- /.box -->




                    </div>
                    <!-- /.col-md-9 -->

                    <div class="col-md-3">
                        <div class="box" id="order-summary">
                            <div class="box-header">
                                <h3>Order summary</h3>
                            </div>
                            <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>

                            <div class="table-responsive">
                                <table id="summary" class="table">
                                    <tbody>
                                        <tr>
                                            <td>Order subtotal</td>
                                            <th>$<?= $total_price ?></th>
                                        </tr>
<?php if (isset($this->coupon_value)): ?>
                                            <tr class="coup">
                                                <td>Coupon</td>
                                                <th><?= "-" . $this->coupon_value . '%' ?></th>
                                            </tr>
<?php endif; ?>
                                        <tr class="total">
                                            <td>Total</td>
                                            <th>$<?php $p = isset($this->coupon_value) ? $this->coupon_value * $total_price / 100 : 0;
echo $total_price - $p; ?></th>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>

                        </div>


                        <div class="box">
                            <div class="box-header">
                                <h4>Coupon code</h4>
                            </div>
                            <p class="text-muted">If you have a coupon code, please enter it in the box below.</p>
                            <form method="get" action="">
                                <div class="input-group">

                                    <input type="text" class="form-control" name="coup">

                                    <span class="input-group-btn">

                                        <button class="btn btn-primary" type="submit"><i class="fa fa-gift"></i></button>

                                    </span>
                                </div>
                                <!-- /input-group -->
                            </form>
                        </div>

                    </div>
                    <!-- /.col-md-3 -->

                </div>
                <!-- /.container -->
            </div>

        </div>
        <!-- /#all -->




        <!-- *** SCRIPTS TO INCLUDE ***
     _________________________________________________________ -->
        <script src="/js/jquery.cookie.js"></script>
        <script src="/js/waypoints.min.js"></script>
        <script src="/js/modernizr.js"></script>
        <script src="/js/owl.carousel.min.js"></script>
        <script src="/js/front.js"></script>
        <script src="/js/sh7ata.js"></script>



    </body>

</html>
